language: csharp
solution: engenious.UI.sln
install:
  - nuget restore engenious.UI.sln
before_script:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo aptitude update
  - sudo aptitude -y -q install ffmpeg
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || true"
  - sleep 3 # give xvfb some time to start
  - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get -y -q install apt-transport-https
  - sudo apt-get -y -q update
  - sudo apt-get -y -q install dotnet-sdk-2.2
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    all_branches: true